# Site/SEO settings
email: junbs95@gmail.com
permalink: /:year/:month/:day/:title/
google_analytics: 

title: BOSEONG FELIPE JEON
description: 'Aerial robotics researcher'
url: http://icsl-Jeon.github.io
baseurl: ""
twitter_username: 
default_img: /assets/IMG_6950.jpg


# Profile settings
name: Boseong Felipe Jeon
profile_img: /assets/IMG_6950.jpg
profile: Doctoral candidate of Seoul national university 
social:
  github: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - octopress-autoprefixer
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - _screenshots
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md

# Pagination
paginate: 5
paginate_path: "/blog/page-:num"

# Sass
sass:
  style: compressed
